services:
  ipanema_sylius_seo_page_plugin.menu.generate:
    class: Ipanema\SyliusSeoPagePlugin\Menu\AdminMenuListener
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
  ipanema_sylius_seo_page_plugin.twig.extension.seo_page:
    class: Ipanema\SyliusSeoPagePlugin\Twig\SeoPageExtension
    arguments:
      - "@ipanema_sylius_seo_page_plugin.repository.seopage"
      - "@sylius.context.channel"
      - "@twig"
    tags:
      - { name: twig.extension }
  ipanema_sylius_seo_page_plugin.form.type.seo_page:
    class: Ipanema\SyliusSeoPagePlugin\Form\Type\SeoPageType
    arguments:
      - "@router.default"
    tags:
      - { name: form.type }
